name: Update Codeforces Problems

on:
  schedule:
    # Run every two weeks (on Monday at 00:00 UTC)
    - cron: '0 0 */14 * *'
  workflow_dispatch:
    # Allow manual trigger from the GitHub Actions tab

jobs:
  update_problems:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run Codeforces scraper
        run: |
          python backend/codeforces_scraper.py
          
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add public/data/codeforces_problems.json
          # Only commit and push if changes were made
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Codeforces problems data" && git push)
